### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by BenjMaq** [hotgluexyz/tap-netsuite#1]
Hi there, 

I was wondering under which license is this tap? Any chance you could add a License file in your repo, similar to other taps? e.g. 
- AGPL - https://github.com/transferwise/pipelinewise-tap-salesforce/blob/master/LICENSE
- Apache 2 - https://github.com/dbt-labs/tap-ebay/blob/master/LICENSE
- MIT - https://gitlab.com/meltano/tap-fastly/-/blob/master/LICENSE
- Other?

thanks!

**Comment by hsyyid** [comment]
@BenjMaq Hi, thanks for the request. Will upload a license shortly. Thanks!
